language: node_js
jobs:
  include:
    - stage: test
      node_js: 6
      script: npm run lint
    - stage: test
      node_js: 7
      script: npm run lint
    - stage: test
      node_js: 8
      script: npm run lint
    - stage: test
      node_js: 9
      script: npm run lint
    - stage: test
      node_js: 10
      script: npm run lint
    - stage: deploy
      node_js: 6
      script:  
        - |
          if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
            chmod +x release.sh
            ./release.sh
          else
            echo "Not PR merge trigger"
          fi